# Generated by Django 4.2.1 on 2023-06-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='checklist',
            name='date',
            field=models.DateField(verbose_name='Date Completed'),
        ),
    ]
