# Generated by Django 4.2.1 on 2023-06-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_bane_alter_checklist_options_alter_checklist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='banes',
            field=models.ManyToManyField(to='main_app.bane'),
        ),
    ]
